const username = 'Ruben'
const password = 'Mercedes'

describe('Order Coffee Automation Testing', () => {
    beforeEach(() => {
        cy.visit('http://localhost:4200/ ')
    })

    // Task a
    it('Customer open the application and see the user login page', () => {
        cy.get('[data-cy="text-title-login"]').should('be.visible')
        cy.get('[data-cy="input-name"]').should('be.visible')
        cy.get('[data-cy="input-password"]').should('be.visible')
        cy.get('[data-cy="btn-login"]').should('be.visible')
    })

    // Task b
    it('Customer can enter their name and password to the available inputs', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
    })

    // Task c
    it('Customer can login by clicking the button “Login” after filling their credentials', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
    })

    it('Customer unable to login without input the username form', () => {
        cy.get('[data-cy="input-password"]').type(password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
    })

    it('Customer unable to login without input the password form', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
    })

    it('Customer can logout by clicking the button “Logout” after login', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get('[data-cy="btn-logout"]').click()
        cy.wait(2000)
    })

    it('Customer login and see the home page', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get('[data-cy="text-navbar-header"]').should('be.visible')
        cy.get('.navbar').should('be.visible')
        cy.get('[data-cy="text-navbar-profile-name"]').should('be.visible')
        cy.get('[data-cy="text-title-menu"]').should('be.visible')
        cy.get('.flex > :nth-child(1) > .card-body').should('be.visible')
        cy.get(':nth-child(2) > .card-body').should('be.visible')
        cy.get(':nth-child(3) > .card-body').should('be.visible')
        cy.get(':nth-child(4) > .card-body').should('be.visible')
        cy.get('[data-cy="text-title-cart"]').should('be.visible')
        cy.get('.card-body > .h-full').should('be.visible')
        cy.get('[data-cy="btn-logout"]').should('be.visible')
    })

    it('Customer able to add item and checkout a Latte', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })

    it('Customer able to add item and checkout a Cappucino', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(2) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })

    it('Customer able to add item and checkout an Expresso', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(3) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })

    it('Customer able to add item and checkout an On The Rock', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(4) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })

    it('Customer able to add all items from the menu to the cart', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(2) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(4) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })

    it('Customer able to add all items from the menu to the cart', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(2) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(4) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })

    it('Customer able to decrease (delete 2 items) from the menu to the cart', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(2) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(4) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(3000)
        cy.scrollTo(0, -500)
        cy.wait(1000)
        cy.get(':nth-child(4) > [data-cy="btn-remove-item-from-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > [data-cy="btn-remove-item-from-cart"]').click()
        cy.wait(3000)
        cy.get('[data-cy="btn-logout"]').click()
        cy.wait(1000)
    })

    it('Customer able to add all items from the menu to the cart', () => {
        cy.get('[data-cy="input-name"]').type(username)
        cy.get('[data-cy="input-name"]').should('have.value',username)
        cy.wait(1000)
        cy.get('[data-cy="input-password"]').type(password)
        cy.get('[data-cy="input-password"]').should('have.value',password)
        cy.wait(1000)
        cy.get('[data-cy="btn-login"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(2) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get(':nth-child(4) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
        cy.wait(1000)
        cy.get('[data-cy="btn-checkout"]').click()
        cy.get('[data-cy="alert-message"]').should('contain', 'Items Purchased')
        cy.wait(3000)
        cy.scrollTo(0, -200)
        cy.wait(1000)
        cy.get('[data-cy="btn-logout"]')
        cy.wait(1000)
    })
    

})